os: linux
sudo: enabled
language: generic

addons:
  apt:
    packages:
     - gnupg wget grep sed qemu-user-static binfmt-support

env:
  - GUIX_SYSTEM=i686-linux
  - GUIX_SYSTEM=x86_64-linux
  - GUIX_SYSTEM=armhf-linux
  - GUIX_SYSTEM=aarch64-linux

before_install:
    - sudo update-binfmts --display qemu-arm
    - sudo update-binfmts --display qemu-aarch64

install:
    - travis_retry wget "https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh?h=v1.0.1" -O guix-install.sh
    - travis_retry gpg --recv-keys 3CE464558A84FDC69DB40CFB090B11993D9AEBB5
    - echo -e 'y\ny' | sudo bash guix-install.sh
    - sudo mkdir -p /var/guix/profiles/per-user/travis
    - sudo chown travis:travis /var/guix/profiles/per-user/travis
    - guix pull --fallback

script:
    - export PATH="~/.config/guix/current/bin${PATH:+:}$PATH"
    - guix build --no-grafts --fallback -f guix.scm --system=$GUIX_SYSTEM

notifications:
    email: false

git:
    depth: 1
